version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    working_directory: ~/project/client
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

workflows:
  build-and-test:
    jobs:
      - test-node
