version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    working_directory: ~/project/client
    steps:
      - checkout:
          path: client
      - run:
          name: verify client folder
          command: ls -a
      - run:
          name: install dependencies
          command: |
            cd client
            yarn install
      - run:
          name: build react app
          command: |
            cd client
            yarn build
      - run:
          name: Run tests
          command: |
            cd client
            yarn vitest run --coverage
  
workflows:
  build-and-test:
    jobs:
      - test-node
