version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - run:
          name: Change directory to client
          command: cd client && yarn install

workflows:
  build-and-test:
    jobs:
      - test-node
