# Use an official Node.js runtime as the base image
FROM node:20.14.0-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Expose the port the React app will run on.
EXPOSE 5173

# Start the React development server
CMD ["yarn", "run", "dev"]
